// DVRMD_Filter.idl : type library source for ActiveX Control project.

// This file will be processed by the MIDL compiler tool to
// produce the type library (DVRMD_Filter.tlb) that will become a resource in
// DVRMD_Filter.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(D040A193-ED38-49B2-AFDE-D10E86A9EFCE), version(1.0),
  helpfile("DVRMD_Filter.hlp"),
  helpstring("DVRMD_Filter ActiveX Control module"),
  control ]
library DVRMD_FilterLib
{
	importlib(STDOLE_TLB);

	//  Primary dispatch interface for CDVRMD_FilterCtrl

	[ uuid(EC35B6AB-684F-4FE3-8EAD-4AAABE024EA2),
	  helpstring("Dispatch interface for DVRMD_Filter Control")]
	dispinterface _DDVRMD_Filter
	{
	properties:

	methods:
			[id(DISPID_ABOUTBOX)] void AboutBox();
			[id(1), helpstring("Open Meida File to Play")] LONG OpenFile(BSTR bstrFile);
			[id(2), helpstring("Login to Media Server")] VARIANT_BOOL Login(BSTR bstrUsername, BSTR bstrPassword, BSTR bstrIP, LONG lPort);
			[id(3), helpstring("Logout from Media Server")] void Logout(void);
			[id(4)] VARIANT_BOOL IsChannelEnable(ULONG lChannel);
			[id(5)] ULONG EnableChannel(ULONG lChannel, VARIANT_BOOL bEnable);
			[id(6)] ULONG SetRenderWindowSize(ULONG lWidth, LONG lHeight);
			[id(7)] ULONG GetRenderWindowSize(LONG* lWidth, LONG* lHeight);
			[id(8)] ULONG GetMediaServer(BSTR* bstrMediaServerIP, LONG* lPort);
			[id(9)] ULONG SetMediaServer(BSTR bstrMediaServerIP, LONG lPort);
	};

	//  Event dispatch interface for CDVRMD_FilterCtrl

	[ uuid(67DC81BA-E0EC-4122-AD13-DEF72A4BEC27),
	  helpstring("Event interface for DVRMD_Filter Control") ]
	dispinterface _DDVRMD_FilterEvents
	{
		properties:
			//  Event interface has no properties

		methods:
			[id(DISPID_DOCLICK)] void DoClick(void);
			[id(DISPID_DBLCLICK)] void DblClick(void);
	};

	//  Class information for CDVRMD_FilterCtrl

	[ uuid(023D5C5C-2FFE-4054-8CE9-45C492778C52),
	  helpstring("DVRMD_Filter Control"), control ]
	coclass DVRMD_Filter
	{
		[default] dispinterface _DDVRMD_Filter;
		[default, source] dispinterface _DDVRMD_FilterEvents;
	};

};
