// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "dvrmd_filterctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CDvrmd_filterctrl1

IMPLEMENT_DYNCREATE(CDvrmd_filterctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CDvrmd_filterctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CDvrmd_filterctrl1 operations
